### ISSUE TITLE
Error during plotting of hotspots

### ISSUE THREAD

**Issue by GM110Z** [art-egorov/ilund4u#2]
Hello

I have been running this on a Mac with M1 chip.  using 

This is the output that i get from debug
○ Visualisation of hotspot communities using lovis4u...
Traceback (most recent call last):
  File "/Users/giusym/miniconda3/lib/python3.10/site-packages/lovis4u/Manager.py", line 137, in load_config
    config = configs.load(path).get_config()
  File "/Users/giusym/miniconda3/lib/python3.10/site-packages/configs/api.py", line 18, in load
    return Config(config_file)
  File "/Users/giusym/miniconda3/lib/python3.10/site-packages/configs/config.py", line 22, in __init__
    self.load(config_file)
  File "/Users/giusym/miniconda3/lib/python3.10/site-packages/configs/config.py", line 52, in load
    with open(config_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'A4p2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/giusym/miniconda3/lib/python3.10/site-packages/ilund4u/drawing.py", line 215, in plot_hotspots
    l_parameters.load_config(self.prms.args["lovis4u_hotspot_config_filename"])
  File "/Users/giusym/miniconda3/lib/python3.10/site-packages/lovis4u/Manager.py", line 169, in load_config
    raise lovis4uError("Unable to parse the specified config file. Please check your config file "
lovis4u.Manager.lovis4uError: Unable to parse the specified config file. Please check your config file or written name.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/giusym/miniconda3/lib/python3.10/site-packages/ilund4u/drawing.py", line 68, in plot_hotspot_communities
    self.plot_hotspots(hc, vis_output_folder, shortest_labels=shortest_labels)
  File "/Users/giusym/miniconda3/lib/python3.10/site-packages/ilund4u/drawing.py", line 257, in plot_hotspots
    raise ilund4u.manager.ilund4uError("Unable to plot set of hotspots using LoVis4u.") from error
ilund4u.manager.ilund4uError: Unable to plot set of hotspots using LoVis4u.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/giusym/miniconda3/bin/ilund4u", line 34, in <module>
    drawing_manager.plot_hotspot_communities(
  File "/Users/giusym/miniconda3/lib/python3.10/site-packages/ilund4u/drawing.py", line 73, in plot_hotspot_communities
    raise ilund4u.manager.ilund4uError("Unable to plot hotspot communities.") from error
ilund4u.manager.ilund4uError: Unable to plot hotspot communities.

I can use LoVis4u as standalone on the same sequences using the same conda environment. The gff files i am using were annotated with prokka. 

By manual annotation, I know the sequences used have at least a P2 hotspot.

**Comment by GM110Z** [comment]
Sorry command i run was
ilund4u hotspots --gff /path/to/gff --debug

**Comment by art-egorov** [comment]
Hi! Thank you for trying iLund4u and this report.
Could you update LoVis4u with the following command: `python3 -m pip install --upgrade lovis4u`, seems you're using one of the older versions. 
I will also modify requirements for lovis4u version with ilund4u installation to avoid such problems.

**Comment by GM110Z** [comment]
Ah yes works perfectly now thank you so much!

**Comment by art-egorov** [comment]
That's great :) 
You can always contact me if any help is needed.

Best,
Artyom
